### ISSUE TITLE
MCP2515 on NRF9160

### ISSUE THREAD

**Issue by Bach-Danielsson** [DejanBukovec/NRF5-SDK-MCP2515#2]
Hi.
Is it possible to run this on NRF9160 , what potential modifications has to be done ?

**Comment by DejanBukovec** [comment]
Hi,
I’m not sure if you can use nRF5 SDK on NRF9160… If yes then you can use this library, maybe you will need to do small changes as one user need to do with nRF52832 device...
If you use nRF Connect SDK which is based on Zephyr RTOS then If remember right you can't directly use that library ... But if remember right nRF Connect SDK already have MCP2515 library available ...
