### ISSUE TITLE
Sending CAN messages.

### ISSUE THREAD

**Issue by martin4951** [DejanBukovec/NRF5-SDK-MCP2515#3]
Hi Dejan,

Thanks for this code, it's helped me a lot.

I am able to receive CAN messages no problem, but when sending with:
`mcp_can_send_msg(uint32_t id, uint8_t ext, uint8_t len, uint8_t *buf);`
Only the CAN message length is received correctly, but the frame ID and data are always 0s.
![CAN_messages](https://user-images.githubusercontent.com/45917319/161276177-6d9ad598-c4ec-43bc-bdf1-4c30273a44d6.PNG)

I noticed you use:
`mcp2515_write_canMsg()`
When sending CAN messages, but there is no implementation for this function in this repository.

**Comment by martin4951** [comment]
Turns out this isn't an issue. Memory manager needs to be enabled in order to send CAN messages.

**Comment by mattalanskas** [comment]
@martin4951 how did you enable memory manager ? I am unable to send messages currently as well on nrf52832 chip

**Comment by DejanBukovec** [comment]
Im not sure if on nrf52832 is same check for:
#define MEM_MANAGER_ENABLED 1
