### ISSUE TITLE
NRF52832 Support

### ISSUE THREAD

**Issue by mattalanskas** [DejanBukovec/NRF5-SDK-MCP2515#5]
Any particular changes to integrate into a nrf52832 project with bluetooth?

**Comment by mattalanskas** [comment]
Getting stuck in here on set up... specifically the while loop

![image](https://user-images.githubusercontent.com/106279373/222836487-2ecb4ec3-d05b-43ea-afee-83a4358d1805.png)

**Comment by mattalanskas** [comment]
Now here

![image](https://user-images.githubusercontent.com/106279373/222842498-1cf3525b-8482-4172-9241-e3e2b7de3ba4.png)

**Comment by DejanBukovec** [comment]
Hi,
Im sorry I don't have nrf52832 to test it... If I remember corectly on NRF forums someone do/modify library for nrf52832 ...
